"""Add attachment_files to homeworks table

Revision ID: 6d524301d151
Revises: 306278b3de7e
Create Date: 2025-08-17 15:03:33.083436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d524301d151'
down_revision = '306278b3de7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_ids', sa.Text(), nullable=True))

    with op.batch_alter_table('homeworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_files', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homeworks', schema=None) as batch_op:
        batch_op.drop_column('attachment_files')

    with op.batch_alter_table('homework_submissions', schema=None) as batch_op:
        batch_op.drop_column('file_ids')

    # ### end Alembic commands ###
